### ISSUE TITLE
Passing scenarioDirectory as an argument to gradle

### ISSUE THREAD

**Issue by anenriquez** [HBRS-MAAS/project#118]
For now, the scenarioDirectory has to be written in the Start.java. Will there be an argument to pass in the scenarioDirectory as an argument?

**Comment by DharminB** [comment]
It is definitely possible to implement that. If all teams want that, we can implement it right away.

**Comment by anenriquez** [comment]
Hi. How is the status on this? Would it be possible to implement it?

**Comment by DharminB** [comment]
There is no progress. I don't know if everyone wants this or not. Could you ask other teams if they want this functionality or not?

**Comment by DharminB** [comment]
This change is now in develop.
