### ISSUE TITLE
The simulation ends after the end time determined in the Start.java

### ISSUE THREAD

**Issue by anenriquez** [HBRS-MAAS/project#127]
The end time for each state has to be manually entered in the Start.java. It is difficult to determine how long the simulation should last for each scenario file and it is most likely different for each of the scenarios. We suggest to take the endtime from the meta file (duration in days).

**Comment by DharminB** [comment]
The order processing agent and dummy agent fails with a longer endtime in travis. However, they work fine in local machine. At this late stage, it would not be possible to integrate this change.
