### ISSUE TITLE
Proposal for order processing messages

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project#19]
- [x] right-brothers: #14 

- [x] commitment_issues: #26

- [x] team_pjt: #16 

- [x] mas-maas: #18

- [ ] Intell-Agent:

- [ ] Team-TRK:

**Comment by argenos** [comment]
@HBRS-MAAS/intell-agent @HBRS-MAAS/mas_maas @HBRS-MAAS/team-trk please make sure to comment in this thread so I can update your proposals

**Comment by anenriquez** [comment]
mas-maas: #18

**Comment by Sushant-Chavan** [comment]
Commitment_issues: #26
