### ISSUE TITLE
Proposals for visualization agent(s)

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project#20]
## Proposals
- [x] right-brothers: #17 
- [x] commitment_issues: #23
- [x] team_pjt: #22
- [x] mas-maas: #21 
- [x] Team-TRK: #24

**Comment by argenos** [comment]
@HBRS-MAAS/commitment_issues @HBRS-MAAS/team_pjt @HBRS-MAAS/intell-agent @HBRS-MAAS/team-trk please comment on this thread so I can update your proposals

**Comment by argenos** [comment]
@HBRS-MAAS/mas_maas is  #21 the right one for your visualization proposal?

**Comment by anenriquez** [comment]
Correction: mas-maas #21

**Comment by janl1992** [comment]
#22 is the visualization proposal for team pjt

**Comment by AbanoubAbdelmalak** [comment]
#23 the visualization for team Commitment_Issues.

**Comment by tmeule2s** [comment]
#24 the visualization proposal for team trk

**Comment by argenos** [comment]
@HBRS-MAAS/ws18 please take a look at all the opened pull requests, and comment on the threads in case you have questions. We'll discuss this and #19 tomorrow.

**Comment by argenos** [comment]
For reference, the agreed upon framework for the visualization components is JavaFX

**Comment by argenos** [comment]
The proposals that were discussed and accepted during class can be found in the follow up issue: #40
