### ISSUE TITLE
Delivery interfaces

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project#32]
Two pull requests are needed:

*  [x]  docs/messages/mailbox.md containing the input and output messages
*   [ ] the mailbox agent, which inherits from the base class

**Comment by Sushant-Chavan** [comment]
Pull request #42 created with proposal for the delivery interface messages

**Comment by Sushant-Chavan** [comment]
Pull request #48 created for adding the mailbox interface agent.
