### ISSUE TITLE
Street network visualization

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project#38]
Show the current location of the truck agents, and in show by truck the contained orders and their estimated delivery time

**Comment by AbanoubAbdelmalak** [comment]
Did not create a pull request because we still did not fix the gradle build problem we have.

**Comment by Sushant-Chavan** [comment]
Pull request #109 created for resolving this issue

**Comment by Sushant-Chavan** [comment]
Released the implemention in pull request #109
