### ISSUE TITLE
Visualization agent

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project#40]
The following visualization proposals were accepted:
* Historical view #34 
* Individual order status #35 
* Message queues by agent #36 
* Order board #37 
* Street network #38 

The pull request should also contain their interfaces added to the base class (#39), so other teams can seamlessly integrate it into their projects.

The selected framework is JavaFX.

**Comment by argenos** [comment]
@HBRS-MAAS to clarify the deadline: although the complete functionality does not need to be there by next week, your messages and a prototype of your agent which can receive them are a good start for this assignment. 

In case you don't want to implement the issue that was assigned to you, please write on this thread so other teams who might be interested can switch if they want. NB some of this might be converted into an assignment later on if not taken up by someone.

**Comment by madmax2012** [comment]
@HBRS-MAAS/team_pjt  Will implement their visualization task

**Comment by tmeule2s** [comment]
did anyone fix the build issue with javafx yet?

**Comment by argenos** [comment]
@HBRS-MAAS/ws18 please make sure that the README contains instructions on how to run your interface agents and visualization components. Remember that only interfaces and visualization that are **merged** and runnable from this repository will be counted. Deadline for this is Thursday 18:00.

**Comment by anenriquez** [comment]
Does the visualization agent should run in this repository? We have created the visualization for the doughPrep stage using the agents of our architecture, i.e., the visualizator not only receives messages from the proofer agent but also from other agents in our internal architecture. If we add visualization to upstream we would also need to include the internal agents of our doughPrep stage to this repository. Is this correct? Thanks!

**Comment by argenos** [comment]
No need to add your project agents here, however, the visualization should run **even if it doesn't receive any updates**. Keep in mind that, at least in theory, your interface agents should talk to your visualization component (I am aware that not all visualizations do this). 

Your interface agents are a different story, those should run, regardless of the existance of your other agents.

**Comment by anenriquez** [comment]
Thanks for the quick reply. Unfortunately, our visualization will not work if it does not receive the messages sent by our agents. I opened a pull request with everything that the visualization needs.  However, we understand if this is not sufficient for getting the visualization points.

**Comment by anenriquez** [comment]
Should we make the pull request to develop or to master? I have opened a new pull request to develop. Should I modify it to be merged into master? Thanks!
