### ISSUE TITLE
Missing slot information for the ovens

### ISSUE THREAD

**Issue by anenriquez** [HBRS-MAAS/project#56]
Hello @argenos it seems the bakery scenarios do not have information about the slots in the ovens. Should we assume that each oven has 4 slots? The PDF with the project description says:  " The bakery has a number of ovens, each of which has 4 equally-sized   baking slots with individual controllable baking temperature" ... For each product, a number of items simultaneously fit into an oven slot." Is there information about the capacity of a slot based on the product type? I cannot find it in the bakery.json scenario. 

Thanks!

**Comment by anenriquez** [comment]
I forgot to mention that the bakeries.json does have "breadsPerOven" according to the product. If we assume there are 4 slots in an oven, we can get the breadsPerSlot.

**Comment by argenos** [comment]
>
>
> Hello @argenos it seems the bakery scenarios do not have information about the slots in the ovens. Should we assume that each oven has 4 slots?

Yes, for now let's assume each oven has 4 tray slots.
> I forgot to mention that the bakeries.json does have "breadsPerOven" according to the product. If we assume there are 4 slots in an oven, we can get the breadsPerSlot.

This refers to the number of breads per tray. I could rename that but then everyone has to update their parsing of the scenario file. Let me know what you prefer.

> Regarding the steps in the recipes. Which are the steps that define the start and end of a production stage? Is it:
>
>     DoughPreparation: from kneading to proofing
>
>     Baking: from baking to cooling
>
>     Packaging: the next step from cooling till the last step
>
> Each stage might have intermediate steps, but are the boundaries like the ones mentioned above? In that case, in bakeries.json, should cooling be before proofing?
I did not have time to fully check this. But in short, yes. Everything between kneading and proofing (inclusive) is dough preparation. Everything between baking and cooling (inclusive) is in the baking stage, and everything **after** cooling is in packaging.

Cooling shouldn't happen before proofing, do you have a line number where that's happening in bakeries.json? 

Sorry for the late reply, seems like my email answer didn't go through.
