### ISSUE TITLE
Bugs in scenario files

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/project#58]
- Repeated product with different information in same bakery. Example : product with `guid: "Bun"` is repeated for same Bakery `Sunspear Bakery` with different `salesPrice`.
- heating and cooling rate for ovens are underscroll seperated rather than camel case. Expected `heatingRate`, found `heating_rate`

**Comment by argenos** [comment]
This will have to wait till Monday unfortunately.

**Comment by argenos** [comment]
@HBRS-MAAS fyi I just pushed a fix for this issue, please update your repositories.
