### ISSUE TITLE
Expected reply by Customer for notFeasibleMessage from OrderProcessing

### ISSUE THREAD

**Issue by widyaaulia** [HBRS-MAAS/project#75]
When the scheduler decide the order is not feasible based on the schedule, what does the order processing expect the customer to send? Order Processing, after sendNotFeasibleMessage(), doesn't increment the step: step = 1. So it stays there and wait for the scheduler to send something. Then, looking at Scheduler, after sending the schedule feasibility to Order Processing, it increments the step to 2 and so it waits for accept_proposal from Order Processing. This problem, I think, won't be just for 'not feasible order'. If the customer reject the proposal, the order processing doesn't tell the Scheduler (DistributeScheduledOrder) which also will make the Scheduler to wait.

I am trying to understand how Order Processing works so how I interpret the code might be wrong.

Any input will be appreciated. Thank you.

**Comment by argenos** [comment]
This has to be solved by team @HBRS-MAAS/team_pjt, I can only merge from here.

**Comment by janl1992** [comment]
Sorry for replying late. Here is my answer to your question.

> Order Processing, after sendNotFeasibleMessage(), doesn't increment the step: step = 1. So it stays there and wait for the scheduler to send something.
-->Yes you are right - I opened a merge Request to master for this. From my point of view this merge request should also fix your other concerns according scheduler. @Dr4gonbl4de Could you please confirm my merge request?

**Comment by janl1992** [comment]
The fix was delivered with [https://github.com/HBRS-MAAS/project/pull/86#issue-239843992]
