### ISSUE TITLE
Add initialiser for orderprocessing agent

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/project#81]
Would it be possible to add initialiser for order processing agent?

We want to test baking and packaging stage with order processor and customer.

I tried adding just `order-processing:org.maas.agents.OrderProcessing` in the `OrderProcessingInitialiser.java` but soon realised that the agent needs 2 arguments.

**Comment by janl1992** [comment]
The initializer is in our Start.class .

**Comment by janl1992** [comment]
Yes. In Start.java our Order Processor and Scheduler is initialized .
