### ISSUE TITLE
Config File (order message) for Order Processing

### ISSUE THREAD

**Issue by widyaaulia** [HBRS-MAAS/project#95]
There is a mistake in how the code read the JSONObject of order, ex. customerId instead of customer_id. Our message is based on the config file. Our team did this review before so it seems the code in class repo hasn't been update.

**Comment by janl1992** [comment]
I can't find the place in our code where we use customerId in an order. From my point of view we only use guid of an order. Can you give me a hint?

**Comment by janl1992** [comment]
Okay I opened a pull request for Order.java to hbrs/maas develop branch #99 . Does this solve your problem?

Kind regards
Jan
