### ISSUE TITLE
BakeryId for Proofer

### ISSUE THREAD

**Issue by janl1992** [HBRS-MAAS/project#98]
Hi 
Would it be possible to assign a bakeryId to the proofer? By now proofer just registers with type proofer. It would be great if proofer could register with type proofer and name bakery id. This way it would be possible that the dough manager is able to dispatch orders only to the proofer with whom he has a bakery id in common. Thank you.

Kind regards
Jan

**Comment by anenriquez** [comment]
Yes, we will address this. The Proofer will register as "Proofer_bakeryID"

**Comment by anenriquez** [comment]
Addressed in 37b184dc1a769e2208411a6d3d3bd00b92648d11
